name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["type/bug"]

body:
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Tell us what happens instead of the expected behavior 
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false